# Site settings
title: Programmer & Freelancer
email: ombarus.dev@gmail.com
url: https://ombarus.com/
description: "Ombarus, Programmer, Game Developper in any language from C/C++/C# to Python & Ruby and even Java. I worked for 8 years in a Mobile Video Game Company in Canada where I worked on everything : Physics, Graphics, AI, Camera, UI and everything in-between."
keywords: "Ombarus, Programmer, C++, Developper, Video Game, Mobile, Mobile App, Freelancer"
skills: "Programmer - C++ - C# - Python"
meta_author: Bouvier Guillaume

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2d2d2a #1e893c
  primary-rgb: "45,45,42" #"30,137,60"
  secondary: 1e893c #353831
  secondary-dark: 353831 #2d2d2a

# Footer settings
footer:
  copyright: Ombarus
  location: Japan
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: linkedin
    url: https://www.linkedin.com/in/guillaume-bouvier-88a4863/
  - title: github
    url: https://github.com/Ombarus

# Postal address (add as many lines as necessary)
address:
  - line: Contact me by email.

# Credits content
credits: 'All content therein is owned by their respective creator. Please ask before you copy, distribute or reproduce anything you find on this website.'

# Build settings
markdown: kramdown
permalink: pretty
